### ISSUE TITLE
Issues when System goes to sleep

### ISSUE THREAD

**Issue by user2745** [shvchk/poly-dark#10]
On occasion,  I put my linux laptop to sleep or the battery accidentally dies, I get a hung black screen.
Since this did not happen before, I wonder if it has anything to do with grub2 or related.

This is not an issue with the script, but more a question if the script caused an issue on my laptop

Laptop: Xiaomi Notebook Pro i7 version
Issue: when waking up from sleep mode, laptop is sometimes in black (console) screen, and unable to escape without restart

**Comment by shvchk** [comment]
It's really hard to tell without more info: OS, logs (`journalctl --since "2021-11-15 09:30:00" > sleep.log` with time just before system goes to sleep), installer script errors (try to reinstall theme and see if it shows any errors).

**Comment by shvchk** [comment]
closing for now, let me know if this is still an issue
