### ISSUE TITLE
Can't detect arch-like distros

### ISSUE THREAD

**Issue by CarterSnich** [shvchk/poly-dark#18]
Script can't detect my Manjaro as an arch-like distro. I `cat`-ted `/etc/os-release`, this is what it looks like:

```zsh
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
```

But, in the script it, checking looks like this:
```sh
  94   │     elif [[ "$ID" =~ (arch|gentoo|artix) || \
  95   │             "$ID_LIKE" =~ (archlinux|gentoo|artixlinux) ]]; then
```

Instead of `archlinux`, my `ID_LIKE` on my `os-release` is `arch`. Can I change it on the script so it can proceed to install? I wanna ask, cos I don't know if it's a valid move. I don't wanna nuke my grub. I still don't know the grub part of Linux.

**Comment by shvchk** [comment]
Thanks, should be fixed now :wink:
