### ISSUE TITLE
add icon to phoenix os

### ISSUE THREAD

**Issue by killerjn** [shvchk/poly-dark#5]
hi I wonder if there is any way to add icon to phoenix os
I installed it in the same partition where I use ubuntu

**Comment by shvchk** [comment]
If there is a GRUB menu entry for it, it's definitely possible to have an icon for it. There are two things needed for that:
1. An icon itself in theme's `icons` directory
2. A reference to that icon in corresponding GRUB menu entry class in `/boot/grub/grub.cfg`. Icon is selected by GRUB based on the *classes* specified for the menu entry in `/boot/grub/grub.cfg` (see [GRUB docs for boot menu](http://www.gnu.org/software/grub/manual/grub/grub.html#Boot-Menu)). That file is autogenerated, but you can alter the generation process with files in `/etc/grub.d`. This [guide for Antegros](https://antergos.com/wiki/miscellaneous/how-to-add-icons-to-antergos-grub-menu-entries-mbr-legacy/) might give a clue (most of it is applicable to other distros as well).

E.g. here are Ubuntu and Windows menu entries from my `/boot/grub/grub.cfg`:

```
menuentry 'Ubuntu' --class ubuntu --class gnu-linux --class gnu --class os [...]
```
```
menuentry 'Windows Boot Manager (on /dev/sdb1)' --class windows --class os [...]
```

See that `--class ubuntu`? That means that GRUB would look for `ubuntu.png` in theme's `icons` directory, and use it if available. For `--class windows` it would look for `windows.png`, for `--class phoenix` it would look for `phoenix.png`, etc.

**Comment by killerjn** [comment]
thanks I only had to edit `/etc/grub.d. `and do `sudo update grub`
![img-20180521-wa0000](https://user-images.githubusercontent.com/32747059/40322012-95799c30-5cf6-11e8-91a1-8cafaee77b9e.jpg)
